config/routes.rb
Fads::Application.routes.draw do
  devise_for :users

  resources :clients, :only => [:new, :create, :show, :index] do
    collection do
      post 'select'
    end

    resources :campaigns, :only => [:index, :new, :create, :show] do
      member do
        get 'available_creatives'
        post 'add_creative'
      end

      resources :campaign_snapshots, :only => [:index, :show]
      resources :facebook_campaigns, :only => [:index, :show]
    end

    resources :creatives
    resources :target_groups, :only => [:new, :create, :show, :index]
  end

  root :to => 'clients#index'

end

app/models/ad.rb
class Creative < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :users
  has_many :campaigns
  has_many :clients
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  belongs_to :client
  has_many :facebook_campaigns
  has_many :campaign_snapshots

  has_and_belongs_to_many :creatives
end

app/models/campaign_result.rb
class CampaignResult < ActiveRecord::Base
  belongs_to :facebook_campaign
  belongs_to :campaign_snapshot  

  def cpc
    (spend/clicks).to_f
  end

end

app/models/campaign_snapshot.rb
class CampaignSnapshot < ActiveRecord::Base
  belongs_to :campaign
  has_many :campaign_results
  
  before_create :record_timestamp

  private
  def record_timestamp
    write_attribute :timestamp, Time.now if timestamp.blank?
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :agency

  has_many :target_groups
  has_many :campaigns
  has_many :creatives
end

app/models/creative.rb
class Creative < ActiveRecord::Base
  mount_uploader :image, CreativeUploader

  validates :name, :presence => true, :uniqueness => true
  validates :title, :presence => true, :length => {:maximum => 25}
  validates :body, :presence => true, :length => {:maximum => 135}
  validates :image, :presence => true
  validates :link_url, :presence => true

  belongs_to :client
  has_and_belongs_to_many :campaigns
end

app/models/facebook_campaign.rb
class FacebookCampaign < ActiveRecord::Base
  belongs_to :campaign
  has_many :campaign_results
  has_many :campaign_snapshots, :through => :campaign_results

  def temporal_cpc
    campaign_results.inject([]) do |memo, cr|
      reduction = memo.inject(0, :+)
      memo << cr.cpc - reduction
    end
  end
end

app/models/target_group.rb
class TargetGroup < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :client
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  belongs_to :agency

  # TODO: Remove this after we implement agency admin abilities
  after_create :link_to_default_agency
  def link_to_default_agency
    agency = Agency.create(:name => "#{email}-Marketing")
    update_attribute(:agency, Agency.first)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  expose(:client)
end

app/controllers/campaign_snapshots_controller.rb
class CampaignSnapshotsController < ApplicationController
  before_filter :authenticate_user!

  expose(:campaign)
  expose(:campaign_snapshots) {campaign.campaign_snapshots}
  expose(:campaign_snapshot)
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_filter :authenticate_user!

  expose(:campaign)
  expose(:campaigns) {client.campaigns}
  expose(:existing_creatives) {campaign.creatives}
  expose(:available_creatives) {client.creatives - campaign.creatives}
  expose(:creative) {client.creatives.find_by_id(params[:creative_id])}

  def create
    if campaign.save
      flash[:notice] = "Campaign successfully created"
      redirect_to [client, campaign]
    else
      render :new
    end
  end

  def add_creative
    if creative
      campaign.creatives << creative
      campaign.save
      flash[:notice] = "Creative added"
    else
      flash[:error] = "Creative does not exist"
    end
    redirect_to [client, campaign]
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_filter :authenticate_user!

  expose(:clients) {current_user.agency.clients}

  def create
    if client.save
      flash[:notice] = "Client successfully created"
      redirect_to client
    else
      render :new
    end
  end

  def select
    if params[:client_id].empty?
      redirect_to new_client_path
    else
      redirect_to client_path(params[:client_id])
    end
  end

  def index
    flash.keep
    if clients.empty?
      redirect_to new_client_path
    else
      redirect_to client_path(clients.first)
    end
  end
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController

  before_filter :authenticate_user!

  expose :creative
  expose(:creatives) { client.creatives }

  def create
    if creative.save
      flash[:notice] = "Creative successfully created"
      redirect_to [client, creative]
    else
      render :new
    end
  end
end

app/controllers/facebook_campaigns_controller.rb
class FacebookCampaignsController < ApplicationController
  before_filter :authenticate_user!

  expose(:campaign)
  expose(:facebook_campaigns) {campaign.facebook_campaigns}
  expose(:facebook_campaign)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/target_groups_controller.rb
class TargetGroupsController < ApplicationController

  before_filter :authenticate_user!

  expose(:target_group)
  expose(:target_groups) {client.target_groups}

  def create
    if target_group.save
      flash[:notice] = "Target group successfully created"
      redirect_to [client, target_group]
    else
      render :new
    end
  end
end

app/controllers/wireframes_controller.rb
class WireframesController < ApplicationController

 # Use this when we have more than one layout
 # layout :choose_layout

 # def choose_layout
 #   case action_name
 #   when *%w(admin_action another_admin_action)
 #     'fads_admin'
 #   else
 #     false
 #   end
 # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def client_options_for_user(user)
    options = user.agency.clients.inject([[nil, nil]]) {|coll, client| coll << [client.name, client.id]}
    options << ['New Client... ', nil]
    selected = client ? client.id : nil
    options_for_select(options, selected)
  end


  def subnav(selected)
    render :partial => 'subnav', :locals => { :selected => selected }
  end

  def subnav_class(link, selected)
    (link == selected) ? 'selected' : ''
  end
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/views/ads/new.html.haml
= form_for ad, :html => { :multipart => true } do |f|
  = f.label :title
  = f.text_field :title

  = f.label :body
  = f.text_field :body

  = f.label :image
  = f.file_field :image

  = f.submit

app/views/campaign_snapshots/_subnav.html.haml
= link_to 'View All', client_campaign_campaign_snapshots_path(client, campaign), :class => subnav_class(:all, selected)
= link_to 'Create New', '#', :class => subnav_class(:new, selected)

app/views/campaign_snapshots/index.html.haml
- content_for :title, "Campaign Snapshots"
- content_for(:subnav) do
  = subnav(:all)

%p 
  A list of all <em>Campaign Snapshots</em> for 
  = campaign.name
  \.

- if !campaign_snapshots.empty?
  %table#campaign_snapshots_table
    %tr
      %th Date
    - campaign_snapshots.each do |campaign_snapshot|
      %tr
        %td= link_to campaign_snapshot.timestamp.strftime('%d/%m/%Y %l:%M'), client_campaign_campaign_snapshot_path(client, campaign, campaign_snapshot)
- else
  %p You have not created any campaign snapshots.

app/views/campaign_snapshots/show.html.haml
- content_for :title, "Campaign Snapshot: #{campaign_snapshot.timestamp.strftime('%d/%m/%Y %l:%M')}"
- content_for :head do
  = javascript_include_tag 'highcharts/highcharts'
- content_for(:subnav) do
  = subnav(:all)

#cumulative-cpc-chart-container

:javascript
  var cumulative_cpc;
  $(document).ready(function(){
    cumulative_cpc = new Highcharts.Chart({
      chart: {renderTo: 'cumulative-cpc-chart-container', type: 'column'},
      legend: { enabled: false},
      title: {text: 'CPC vs Facebook Campaign'},
      xAxis: {
        title: {text: 'Facebook Campaign'},
        categories: #{campaign_snapshot.campaign_results.map(&:facebook_campaign_id).to_json}
      },
      yAxis: {title: {text: 'CPC'}},
      series: [{data: #{campaign_snapshot.campaign_results.map(&:cpc).to_json}}],
      tooltip: {
         formatter: function() {
            return 'Facebook Campaign: ' + this.x;
         }
      },      
    });
  });

app/views/campaigns/_add_creatives_listing.html.haml
- if !available_creatives.empty?
  %table{ :id => "available_creatives_table" }
    %tr
      %th Name
      %th Title
      %th Body
      %th Landing Page
      %th Image
      %th
    - available_creatives.each do |creative|
      %tr
        %td= creative.name
        %td= creative.title
        %td= creative.body
        %td= creative.link_url
        %td= image_tag creative.image_url(:scaled)
        %td
          = form_tag add_creative_client_campaign_path(client, campaign), :class => 'hidden' do
            = hidden_field_tag 'creative_id', creative.id
            = submit_tag 'Add'
- else
  %p No creatives available to add to this campaign

app/views/campaigns/_subnav.html.haml
= link_to 'View All', client_campaigns_path(client), :class => subnav_class(:all, selected)
= link_to 'Create New', new_client_campaign_path(client), :class => subnav_class(:new, selected)

app/views/campaigns/available_creatives.html.haml
= render :partial => 'add_creatives_listing'

app/views/campaigns/index.html.haml
- content_for :title, "Campaigns"
- content_for(:subnav) do
  = subnav(:all)

%p 
  A list of all <em>Campaigns</em> for 
  = client.name
  \.

- if !campaigns.empty?
  %table#campaigns_table
    %tr
      %th Name
    - campaigns.each do |campaign|
      %tr
        %td= link_to campaign.name, client_campaign_path(client, campaign)
- else
  %p You have not created any campaigns.

app/views/campaigns/new.html.haml
- content_for(:title, "Create a New Campaign")
- content_for(:subnav) do
  = link_to 'View All', client_campaigns_path(client)
  %a.selected Create New

%p A <em>Campaign</em> is a set of Facebook ads that endeavor to achieve a stated goal e.g. (increase email newsletter signups).

= form_for [client, campaign] do |f|
  %fieldset
    %legend Campaign Information
    .required.field
      = f.label :name
      %small= f.error_message_on :name
      = f.text_field :name

  = f.submit

app/views/campaigns/show.html.haml
- content_for :title, campaign.name
- content_for(:head) do
  = javascript_include_tag 'facebox'

- content_for(:subnav) do
  = subnav(:show)

= link_to 'Campaign Snapshots', client_campaign_campaign_snapshots_path(client, campaign)
%br
%br
= link_to 'Facebook Campaigns', client_campaign_facebook_campaigns_path(client, campaign)
%br
%br

%h2 Creatives
= link_to 'Add existing creative', available_creatives_client_campaign_path(client, campaign), :id => 'add_existing_creative', :rel => 'facebox'
|
= link_to 'Add new creative', '#'

- if !existing_creatives.empty?
  = render :partial => 'creatives/listing', :locals => {:creatives => existing_creatives}
- else
  %p You haven't yet added any creatives to this campaign

#add_creative_modal{:style => 'display:none;'}
  = render :partial => 'add_creatives_listing', :locals => {:available_creatives => available_creatives}

:javascript
  jQuery(document).ready(function($) {
    $('a#add_existing_creative')[0].href = '#add_creative_modal';
    $('a[rel*=facebox]').facebox();
  })

app/views/clients/_subnav.html.haml
= link_to 'Create New', new_client_path, :class => subnav_class(:new, selected)

app/views/clients/new.html.haml
- content_for(:title, "New Client")
- content_for(:subnav) do
  = subnav(:new)

%p A <em>Client</em> is an organization that you are running Facebook campaigns for.
= form_for client do |f|
  %fieldset
    %legend Client Information
    .required.field
      = f.label :name
      %small= f.error_message_on :name
      = f.text_field :name

  = f.submit

app/views/creatives/_listing.html.haml
%table{ :id => "creatives_table" }
  %tr
    %th Name
    %th Title
    %th Body
    %th Landing Page
    %th Image
  - creatives.each do |creative|
    %tr
      %td= creative.name
      %td= creative.title
      %td= creative.body
      %td= creative.link_url
      %td= image_tag creative.image_url(:scaled)

app/views/creatives/_subnav.html.haml
= link_to 'View All', client_creatives_path(client), :class => subnav_class(:all, selected)
= link_to 'Create New', new_client_creative_path(client), :class => subnav_class(:new, selected)

app/views/creatives/index.html.haml
- content_for :title, "My Creatives"
- content_for(:subnav) do
  = subnav(:all)

%p A list of all <em>Creatives</em> available for use in your campaigns.

- if !creatives.empty?
  = render :partial => 'listing'
- else
  %p You have not uploaded any creatives.

app/views/creatives/new.html.haml
- content_for(:title, "Create a New Creative")
- content_for(:subnav) do
  = subnav(:new)
%p A <em>Creative</em> consists of the copy and image required to display a single ad.

= form_for [client, creative], :html => { :multipart => true } do |f|
  %fieldset
    %legend Creative Information
    .required.field
      = f.label :name
      %small= f.error_message_on :name
      = f.text_field :name
    
    .required.field
      = f.label :title
      %small= f.error_message_on :title
      = f.text_field :title
      .error_message "are you sure?"

    .required.field
      = f.label :body
      %small= f.error_message_on :body
      = f.text_field :body

    .required.field
      = f.label :link_url, 'Link'
      %small= f.error_message_on :link_url
      = f.text_field :link_url
      .error_message "are you sure?"

    .required.field
      = f.label :image
      %small= f.error_message_on :image
      = f.file_field :image

  = f.submit

app/views/creatives/show.html.haml
= creative.title

= creative.body

= image_tag creative.image_url(:scaled)

app/views/facebook_campaigns/_subnav.html.haml
= link_to 'View All', client_campaign_facebook_campaigns_path(client, campaign), :class => subnav_class(:all, selected)
= link_to 'Create New', '#', :class => subnav_class(:new, selected)

app/views/facebook_campaigns/index.html.haml
- content_for :title, "Facebook Campaigns"
- content_for(:subnav) do
  = subnav(:all)

%p 
  A list of all <em>Facebook Campaigns</em> for 
  = campaign.name
  \.

- if !facebook_campaigns.empty?
  %table#facebook_campaigns_table
    %tr
      %th Name
    - facebook_campaigns.each do |facebook_campaign|
      %tr
        %td= link_to facebook_campaign.name, client_campaign_facebook_campaign_path(client, campaign, facebook_campaign)
- else
  %p You have not created any Facebook campaigns

app/views/facebook_campaigns/show.html.haml
- content_for :title, facebook_campaign.name
- content_for :head do
  = javascript_include_tag 'highcharts/highcharts'
- content_for(:subnav) do
  = subnav(:show)

#cpc-chart-container

:javascript
  var cpc_chart;
  $(document).ready(function(){
    cpc_cahrt = new Highcharts.Chart({
      chart: {renderTo: 'cpc-chart-container', type: 'line'},
      title: {text: 'CPC vs Changein CPC'},
      xAxis: { categories: #{facebook_campaign.campaign_snapshots.map{|x| x.timestamp.strftime('%d/%m/%Y')}}},
      yAxis: {title: {text: 'CPC'}},
      series: [
        {name: 'Cumulative', data: #{facebook_campaign.campaign_results.map(&:cpc).to_json}},
        {name: 'Temporal', data: #{facebook_campaign.temporal_cpc.to_json}}
      ]
    });
  });

app/views/target_groups/_subnav.html.haml
= link_to 'View All', client_target_groups_path(client), :class => subnav_class(:all, selected)
= link_to 'Create New', new_client_target_group_path(client), :class => subnav_class(:new, selected)

app/views/target_groups/index.html.haml
- content_for :title, "Target Groups"
- content_for(:subnav) do
  = subnav(:all)

%p A list of all <em>Target Groups</em> available for use in your campaigns.

- if !target_groups.empty?
  %table{ :id => "target_groups_table" }
    %tr
      %th Name
      %th Actions
    - target_groups.each do |target_group|
      %tr
        %td= target_group.name
        %td= link_to 'View', client_target_group_path(target_group)
- else
  %p You have not created any target groups.

app/views/target_groups/new.html.haml
- content_for(:title, "Create a New Target Group")
- content_for(:subnav) do
  = link_to 'View All', client_target_groups_path(client)
  %a.selected Create New
%p A <em>Target Group</em> is a set of variables upon which you want to split test data.

= form_for [client, target_group] do |f|
  %fieldset
    %legend Target Group Criteria
    .required.field
      = f.label :name
      %small= f.error_message_on :name
      = f.text_field :name

  = f.submit 'Create Target Group'