config/routes.rb
Fads::Application.routes.draw do
  devise_for :users

  resources :clients, :only => [:new, :create, :show, :index] do
    collection do
      post 'select'
    end

    resources :campaigns, :only => [:index, :new, :create, :show] do
      member do
        get 'available_creatives'
        post 'add_creative'
      end

      resources :campaign_snapshots, :only => [:index, :show]
      resources :facebook_campaigns, :only => [:index, :show]
    end

    resources :creatives
    resources :target_groups, :only => [:new, :create, :show, :index]
  end

  root :to => 'clients#index'

end

app/models/ad.rb
class Creative < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :users
  has_many :campaigns
  has_many :clients
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  belongs_to :client
  has_many :facebook_campaigns
  has_many :campaign_snapshots

  has_and_belongs_to_many :creatives
end

app/models/campaign_result.rb
class CampaignResult < ActiveRecord::Base
  belongs_to :facebook_campaign
  belongs_to :campaign_snapshot  

  def cpc
    (spend/clicks).to_f
  end

end

app/models/campaign_snapshot.rb
class CampaignSnapshot < ActiveRecord::Base
  belongs_to :campaign
  has_many :campaign_results
  
  before_create :record_timestamp

  private
  def record_timestamp
    write_attribute :timestamp, Time.now if timestamp.blank?
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :agency

  has_many :target_groups
  has_many :campaigns
  has_many :creatives
end

app/models/creative.rb
class Creative < ActiveRecord::Base
  mount_uploader :image, CreativeUploader

  validates :name, :presence => true, :uniqueness => true
  validates :title, :presence => true, :length => {:maximum => 25}
  validates :body, :presence => true, :length => {:maximum => 135}
  validates :image, :presence => true
  validates :link_url, :presence => true

  belongs_to :client
  has_and_belongs_to_many :campaigns
end

app/models/facebook_campaign.rb
class FacebookCampaign < ActiveRecord::Base
  belongs_to :campaign
  has_many :campaign_results
  has_many :campaign_snapshots, :through => :campaign_results

  def temporal_cpc
    campaign_results.inject([]) do |memo, cr|
      reduction = memo.inject(0, :+)
      memo << cr.cpc - reduction
    end
  end
end

app/models/target_group.rb
class TargetGroup < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :client
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  belongs_to :agency

  # TODO: Remove this after we implement agency admin abilities
  after_create :link_to_default_agency
  def link_to_default_agency
    agency = Agency.create(:name => "#{email}-Marketing")
    update_attribute(:agency, Agency.first)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  expose(:client)
end

app/controllers/campaign_snapshots_controller.rb
class CampaignSnapshotsController < ApplicationController
  before_filter :authenticate_user!

  expose(:campaign)
  expose(:campaign_snapshots) {campaign.campaign_snapshots}
  expose(:campaign_snapshot)
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_filter :authenticate_user!

  expose(:campaign)
  expose(:campaigns) {client.campaigns}
  expose(:existing_creatives) {campaign.creatives}
  expose(:available_creatives) {client.creatives - campaign.creatives}
  expose(:creative) {client.creatives.find_by_id(params[:creative_id])}

  def create
    if campaign.save
      flash[:notice] = "Campaign successfully created"
      redirect_to [client, campaign]
    else
      render :new
    end
  end

  def add_creative
    if creative
      campaign.creatives << creative
      campaign.save
      flash[:notice] = "Creative added"
    else
      flash[:error] = "Creative does not exist"
    end
    redirect_to [client, campaign]
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_filter :authenticate_user!

  expose(:clients) {current_user.agency.clients}

  def create
    if client.save
      flash[:notice] = "Client successfully created"
      redirect_to client
    else
      render :new
    end
  end

  def select
    if params[:client_id].empty?
      redirect_to new_client_path
    else
      redirect_to client_path(params[:client_id])
    end
  end

  def index
    flash.keep
    if clients.empty?
      redirect_to new_client_path
    else
      redirect_to client_path(clients.first)
    end
  end
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController

  before_filter :authenticate_user!

  expose :creative
  expose(:creatives) { client.creatives }

  def create
    if creative.save
      flash[:notice] = "Creative successfully created"
      redirect_to [client, creative]
    else
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/target_groups_controller.rb
class TargetGroupsController < ApplicationController

  before_filter :authenticate_user!

  expose(:target_group)
  expose(:target_groups) {client.target_groups}

  def create
    if target_group.save
      flash[:notice] = "Target group successfully created"
      redirect_to [client, target_group]
    else
      render :new
    end
  end
end

app/controllers/wireframes_controller.rb
class WireframesController < ApplicationController

 # Use this when we have more than one layout
 # layout :choose_layout

 # def choose_layout
 #   case action_name
 #   when *%w(admin_action another_admin_action)
 #     'fads_admin'
 #   else
 #     false
 #   end
 # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def client_options_for_user(user)
    options = user.agency.clients.inject([[nil, nil]]) {|coll, client| coll << [client.name, client.id]}
    options << ['New Client... ', nil]
    selected = client ? client.id : nil
    options_for_select(options, selected)
  end


  def subnav(selected)
    render :partial => 'subnav', :locals => { :selected => selected }
  end

  def subnav_class(link, selected)
    (link == selected) ? 'selected' : ''
  end
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "#{yield :title} | FADS"
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = javascript_include_tag 'jquery'
    = csrf_meta_tag
    = yield :head
  %body
    #navigation-container
      - if user_signed_in?
        = form_tag select_clients_path, :id => 'client_select' do
          %label{:for => 'client_id'}
            %strong Current client:
          = select_tag 'client_id', client_options_for_user(current_user)
      #navigation
        - if user_signed_in? && client.id?
          = link_to 'Dashboard', clients_path
          = link_to 'Campaigns', client_campaigns_path(client)
          = link_to 'Target Groups', client_target_groups_path(client)
          = link_to 'Creatives', client_creatives_path(client)
        - if user_signed_in?
          = link_to "Account (#{current_user.email})", "/profile"
          = link_to 'Logout', destroy_user_session_path
        - else
          = link_to 'Login', new_user_session_path
    #subnav-container
      %a{ :href => root_path }
        %img{ :src => "http://www.smartlogicsolutions.com/images/logo.png", :height => 39, :width => 253, :alt => "FADS Logo" }
      #subnav= yield :subnav
    %h1= yield :title
    -if notice
      .notice= notice
    -if alert
      .alert= alert
    #content
      = yield
    #footer
      &copy; 2011 FADS, LLC. All rights reserved. Terms and conditions, features, support, pricing and service options subject to change without notice. |
      %a{ :href => "#"} Terms
      |
      %a{ :href => "#"} Privacy
      |
      %a{ :href => "#"} Policy
      |

  :javascript
    $('select#client_id').change( function() {
      $('form#client_select').submit();
    });